# Joystick Device
dev_path: /dev/input/js0
# Rumble HID
hid_path: /dev/hidraw2
# Frequency Hz
frequency: 500

debug: false
enable_rumble: true

axis_map:
  LX: 0
  LY: 1
  LT: 5  # Left Trigger
  RX: 2
  RY: 3
  RT: 4  # Right Trigger
  DPadX: 6
  DPadY: 7

button_map:
  A: 0
  B: 1
  X: 3
  Y: 4
  LB: 6  # Left Bumper
  RB: 7  # Right Bumper
  Disarm: 10
  Arm: 11
  Xbox: 12  # Xbox button
  LS: 13
  RS: 14

## bitbot config
# url: ws://127.0.0.1:12888/console
url: ws://192.168.1.118:12888/console
vel_scale: [1.0, 1.0, 1.0]

